# Site settings
title: Log Analysis Reports
description: This is a repository of parsed log data from Botify for Payscale.

# The theme is what Jekyll uses to apply styling and a layout
# This is a theme provided by GitHub and works out of the box
theme: jekyll-theme-cayman

# If you have custom CSS or other assets, you'd configure them here
# but for a basic setup, this is not needed.
