# Site settings
title: Log Analysis Reports
description: This is a repository which parses log data [using this tool](https://colab.research.google.com/drive/1x0S9XcJ5iULEcM8frDPNpoP1qnSzdCRa?usp=sharing)

# The theme is what Jekyll uses to apply styling and a layout
# This is a theme provided by GitHub and works out of the box
theme: jekyll-theme-cayman

# If you have custom CSS or other assets, you'd configure them here
# but for a basic setup, this is not needed.
